"""
Policy Revision Engine component for generating improved policy text.

This module implements the PolicyRevisionEngine that generates revised policy
text addressing identified gaps. It uses constrained LLM prompting to inject
new clauses for missing subcategories and strengthen existing clauses for
partial coverage while preserving the original policy structure and tone.

**Validates: Requirements 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8**
"""

import logging
from typing import List, Dict, Optional

from models.domain import (
    ParsedDocument,
    GapDetail,
    Revision,
    RevisedPolicy,
    CSFSubcategory
)
from analysis.llm_runtime import LLMRuntime
from reference_builder.reference_catalog import ReferenceCatalog


logger = logging.getLogger(__name__)


# Mandatory human-review warning text from Requirement 10.8
MANDATORY_WARNING = """
---

## IMPORTANT: Human Review Required

**This revised policy was generated by an AI system and is provided as a draft baseline only.**

The CIS MS-ISAC templates are advisory and may not reflect the most recent applicable standards or your organization's specific legal, regulatory, or operational requirements.

**This document MUST be reviewed, validated, and approved by qualified legal counsel, compliance officers, and security leadership before adoption.**

---
"""


class PolicyRevisionEngine:
    """Generates improved policy text addressing identified gaps.
    
    The engine uses constrained LLM prompting to:
    - Inject new clauses for Missing CSF subcategories
    - Strengthen existing clauses for Partially Covered subcategories
    - Preserve original policy structure and tone
    - Cite CSF subcategory for each revision
    - Append mandatory human-review disclaimer
    
    All revisions use low temperature (0.1) for conservative, factual outputs.
    
    Attributes:
        llm: LLM runtime for text generation
        catalog: Reference catalog for CSF subcategory details
        temperature: LLM temperature for revision generation (default: 0.1)
    """
    
    def __init__(
        self,
        llm: LLMRuntime,
        catalog: ReferenceCatalog,
        temperature: float = 0.1
    ):
        """Initialize policy revision engine.
        
        Args:
            llm: LLM runtime for text generation
            catalog: Reference catalog of CSF subcategories
            temperature: LLM temperature for conservative revisions (default: 0.1)
        """
        self.llm = llm
        self.catalog = catalog
        self.temperature = temperature
        
        logger.info(
            f"Initialized PolicyRevisionEngine with temperature={temperature}"
        )
    
    def revise(
        self,
        original_policy: ParsedDocument,
        gaps: List[GapDetail]
    ) -> RevisedPolicy:
        """Generate revised policy addressing all identified gaps.
        
        This method orchestrates the complete revision process:
        1. Group gaps by revision type (injection vs strengthening)
        2. Generate revisions for each gap
        3. Integrate revisions into original policy text
        4. Append mandatory human-review warning
        5. Track all revisions for transparency
        
        Args:
            original_policy: Original parsed policy document
            gaps: Identified gaps from gap analysis
            
        Returns:
            RevisedPolicy with improved text and revision tracking
            
        Raises:
            ValueError: If original_policy or gaps is invalid
            RuntimeError: If revision generation fails
        """
        if not original_policy or not original_policy.text:
            raise ValueError("original_policy must have text content")
        
        if not gaps:
            logger.warning("No gaps provided, returning original policy with warning")
            return RevisedPolicy(
                original_text=original_policy.text,
                revised_text=original_policy.text + MANDATORY_WARNING,
                revisions=[],
                warning=MANDATORY_WARNING.strip(),
                metadata={
                    'revision_count': 0,
                    'injection_count': 0,
                    'strengthening_count': 0
                }
            )
        
        logger.info(f"Starting policy revision for {len(gaps)} gaps")
        
        # Separate gaps by type
        missing_gaps = [g for g in gaps if g.status == 'missing']
        partial_gaps = [g for g in gaps if g.status == 'partially_covered']
        
        logger.info(
            f"Gap breakdown: {len(missing_gaps)} missing, "
            f"{len(partial_gaps)} partially covered"
        )
        
        # Generate revisions
        revisions = []
        
        # Process missing gaps (inject new clauses)
        for gap in missing_gaps:
            try:
                revision = self._inject_clause(original_policy, gap)
                revisions.append(revision)
            except Exception as e:
                logger.error(
                    f"Failed to inject clause for {gap.subcategory_id}: {e}"
                )
                # Continue with other revisions
                continue
        
        # Process partial gaps (strengthen existing clauses)
        for gap in partial_gaps:
            try:
                revision = self._strengthen_clause(original_policy, gap)
                revisions.append(revision)
            except Exception as e:
                logger.error(
                    f"Failed to strengthen clause for {gap.subcategory_id}: {e}"
                )
                # Continue with other revisions
                continue
        
        logger.info(f"Generated {len(revisions)} revisions")
        
        # Integrate revisions into policy text
        revised_text = self._integrate_revisions(
            original_policy.text,
            revisions
        )
        
        # Append mandatory warning
        revised_text = self.append_warning(revised_text)
        
        # Build metadata
        metadata = {
            'revision_count': len(revisions),
            'injection_count': len(missing_gaps),
            'strengthening_count': len(partial_gaps),
            'temperature': self.temperature
        }
        
        result = RevisedPolicy(
            original_text=original_policy.text,
            revised_text=revised_text,
            revisions=revisions,
            warning=MANDATORY_WARNING.strip(),
            metadata=metadata
        )
        
        logger.info(
            f"Policy revision complete: {len(revisions)} revisions applied"
        )
        
        return result
    
    def _inject_clause(
        self,
        policy: ParsedDocument,
        gap: GapDetail
    ) -> Revision:
        """Generate new policy clause for missing subcategory.
        
        Uses LLM to generate a new policy clause that addresses the missing
        CSF subcategory while matching the tone and structure of the original
        policy.
        
        Args:
            policy: Original policy document for context
            gap: Gap detail for missing subcategory
            
        Returns:
            Revision object with new clause
            
        Raises:
            RuntimeError: If clause generation fails
        """
        logger.debug(f"Injecting clause for {gap.subcategory_id}")
        
        # Get subcategory details from catalog
        subcategory = self.catalog.get_subcategory(gap.subcategory_id)
        
        # Determine appropriate section for injection
        section = self._determine_section(policy, gap, subcategory)
        
        # Build prompt for clause injection
        prompt = self._build_injection_prompt(
            policy_excerpt=self._get_policy_excerpt(policy, section),
            gap=gap,
            subcategory=subcategory
        )
        
        # Generate new clause
        try:
            new_clause = self.llm.generate(
                prompt=prompt,
                temperature=self.temperature,
                max_tokens=512
            )
        except Exception as e:
            raise RuntimeError(
                f"Failed to generate clause for {gap.subcategory_id}: {e}"
            )
        
        # Create revision object
        revision = Revision(
            section=section,
            gap_addressed=gap.subcategory_id,
            original_clause="",  # No original clause for injection
            revised_clause=new_clause.strip(),
            revision_type="injection"
        )
        
        logger.debug(
            f"Generated injection for {gap.subcategory_id} in section '{section}'"
        )
        
        return revision
    
    def _strengthen_clause(
        self,
        policy: ParsedDocument,
        gap: GapDetail
    ) -> Revision:
        """Improve existing clause for partial coverage.
        
        Uses LLM to strengthen an existing policy clause that partially
        addresses a CSF subcategory, preserving the original intent while
        adding missing elements.
        
        Args:
            policy: Original policy document
            gap: Gap detail for partially covered subcategory
            
        Returns:
            Revision object with strengthened clause
            
        Raises:
            RuntimeError: If clause strengthening fails
        """
        logger.debug(f"Strengthening clause for {gap.subcategory_id}")
        
        # Get subcategory details from catalog
        subcategory = self.catalog.get_subcategory(gap.subcategory_id)
        
        # Extract original clause from evidence quote
        original_clause = gap.evidence_quote or "No specific clause identified"
        
        # Determine section
        section = self._determine_section(policy, gap, subcategory)
        
        # Build prompt for clause strengthening
        prompt = self._build_strengthening_prompt(
            original_clause=original_clause,
            gap=gap,
            subcategory=subcategory
        )
        
        # Generate strengthened clause
        try:
            strengthened_clause = self.llm.generate(
                prompt=prompt,
                temperature=self.temperature,
                max_tokens=512
            )
        except Exception as e:
            raise RuntimeError(
                f"Failed to strengthen clause for {gap.subcategory_id}: {e}"
            )
        
        # Create revision object
        revision = Revision(
            section=section,
            gap_addressed=gap.subcategory_id,
            original_clause=original_clause,
            revised_clause=strengthened_clause.strip(),
            revision_type="strengthening"
        )
        
        logger.debug(
            f"Generated strengthening for {gap.subcategory_id} in section '{section}'"
        )
        
        return revision
    
    def append_warning(self, revised_text: str) -> str:
        """Append mandatory human-review disclaimer to revised policy.
        
        Args:
            revised_text: Revised policy text
            
        Returns:
            Policy text with appended warning
        """
        return revised_text + MANDATORY_WARNING
    
    def _build_injection_prompt(
        self,
        policy_excerpt: str,
        gap: GapDetail,
        subcategory: CSFSubcategory
    ) -> str:
        """Build prompt for injecting new policy clause.
        
        Args:
            policy_excerpt: Relevant excerpt from original policy
            gap: Gap detail
            subcategory: CSF subcategory details
            
        Returns:
            Formatted prompt for LLM
        """
        prompt = f"""You are a cybersecurity policy expert. Generate a new policy clause to address a missing NIST CSF 2.0 requirement.

**Original Policy Excerpt (for tone and structure reference):**
{policy_excerpt}

**Missing CSF Subcategory:**
ID: {subcategory.subcategory_id}
Function: {subcategory.function}
Category: {subcategory.category}
Description: {subcategory.description}

**Gap Explanation:**
{gap.gap_explanation}

**Suggested Fix:**
{gap.suggested_fix}

**Instructions:**
1. Write a new policy clause that addresses the missing CSF subcategory
2. Match the tone, style, and structure of the original policy
3. Be specific and actionable
4. Include a citation to the CSF subcategory (e.g., "This addresses NIST CSF {subcategory.subcategory_id}")
5. Keep the clause concise (2-4 sentences)

**New Policy Clause:**"""
        
        return prompt
    
    def _build_strengthening_prompt(
        self,
        original_clause: str,
        gap: GapDetail,
        subcategory: CSFSubcategory
    ) -> str:
        """Build prompt for strengthening existing policy clause.
        
        Args:
            original_clause: Original policy clause text
            gap: Gap detail
            subcategory: CSF subcategory details
            
        Returns:
            Formatted prompt for LLM
        """
        prompt = f"""You are a cybersecurity policy expert. Strengthen an existing policy clause to fully address a NIST CSF 2.0 requirement.

**Original Policy Clause:**
{original_clause}

**CSF Subcategory (Partially Covered):**
ID: {subcategory.subcategory_id}
Function: {subcategory.function}
Category: {subcategory.category}
Description: {subcategory.description}

**Gap Explanation:**
{gap.gap_explanation}

**Suggested Fix:**
{gap.suggested_fix}

**Instructions:**
1. Preserve the original clause's intent and structure
2. Add missing elements to fully address the CSF subcategory
3. Maintain the original tone and style
4. Be specific and actionable
5. Include a citation to the CSF subcategory (e.g., "This addresses NIST CSF {subcategory.subcategory_id}")
6. Keep the strengthened clause concise

**Strengthened Policy Clause:**"""
        
        return prompt
    
    def _determine_section(
        self,
        policy: ParsedDocument,
        gap: GapDetail,
        subcategory: CSFSubcategory
    ) -> str:
        """Determine appropriate section for revision.
        
        Uses policy structure and CSF category to determine where the
        revision should be placed.
        
        Args:
            policy: Original policy document
            gap: Gap detail
            subcategory: CSF subcategory details
            
        Returns:
            Section name for revision placement
        """
        # Try to match CSF category to policy section
        if policy.structure and policy.structure.sections:
            for section in policy.structure.sections:
                # Simple keyword matching
                if subcategory.category.lower() in section.title.lower():
                    return section.title
                if subcategory.function.lower() in section.title.lower():
                    return section.title
        
        # Fallback to CSF category as section name
        return subcategory.category
    
    def _get_policy_excerpt(
        self,
        policy: ParsedDocument,
        section_name: str,
        max_length: int = 1000
    ) -> str:
        """Get relevant policy excerpt for context.
        
        Args:
            policy: Policy document
            section_name: Target section name
            max_length: Maximum excerpt length
            
        Returns:
            Policy excerpt text
        """
        # Try to find matching section
        if policy.structure and policy.structure.sections:
            for section in policy.structure.sections:
                if section.title == section_name:
                    excerpt = section.content[:max_length]
                    if len(section.content) > max_length:
                        excerpt += "..."
                    return excerpt
        
        # Fallback to beginning of policy
        excerpt = policy.text[:max_length]
        if len(policy.text) > max_length:
            excerpt += "..."
        return excerpt
    
    def _integrate_revisions(
        self,
        original_text: str,
        revisions: List[Revision]
    ) -> str:
        """Integrate revisions into original policy text.
        
        This method creates a revised policy document by adding revision
        sections. For simplicity, revisions are appended by section rather
        than attempting complex text replacement.
        
        Args:
            original_text: Original policy text
            revisions: List of revisions to integrate
            
        Returns:
            Integrated policy text with revisions
        """
        # Group revisions by section
        revisions_by_section: Dict[str, List[Revision]] = {}
        for revision in revisions:
            if revision.section not in revisions_by_section:
                revisions_by_section[revision.section] = []
            revisions_by_section[revision.section].append(revision)
        
        # Build revised text
        revised_text = original_text + "\n\n"
        revised_text += "# Policy Revisions\n\n"
        revised_text += "The following revisions address identified gaps in NIST CSF 2.0 coverage:\n\n"
        
        for section, section_revisions in revisions_by_section.items():
            revised_text += f"## {section}\n\n"
            
            for revision in section_revisions:
                if revision.revision_type == "injection":
                    revised_text += f"**New Clause (addresses {revision.gap_addressed}):**\n\n"
                    revised_text += f"{revision.revised_clause}\n\n"
                else:  # strengthening
                    revised_text += f"**Strengthened Clause (addresses {revision.gap_addressed}):**\n\n"
                    if revision.original_clause:
                        revised_text += f"*Original:* {revision.original_clause}\n\n"
                    revised_text += f"*Revised:* {revision.revised_clause}\n\n"
        
        return revised_text
    
    def __repr__(self) -> str:
        """String representation of policy revision engine."""
        return f"PolicyRevisionEngine(temperature={self.temperature})"
